cnn0_units: 64
cnn1_units: 128
lstm0_units: 50
lstm1_units: 30
lstm2_units: 20
lag: 5
points_per_call: 20
regularizers_l2: 0.2
recurrent_dropout_rate: 0.2
activation: 'relu'
optimizer: 'adam'
epochs: 20
points_to_predict: 288
